In [3]:
import numpy as np

In [2]:
lst1=(2,3)
lst2=(4,6)

a=np.array(lst1)
b=np.array(lst2)

a+b

array([6, 9])

In [47]:
multy=list(map(lambda x,y:x*y, lst1, lst2))
print(multy)

[8, 18, 28]


In [82]:
lst5=[(1,2), (4,5)]
a=np.array(lst5)
a

array([[1, 2],
       [4, 5]])

In [36]:
a=np.array(lst1)
b=np.array(lst2)
c=a*b
print(c)


In [ ]:

a=np.array(lst1)
b=np.array(lst2)
c=a/b
print(c)


In [146]:

a=np.arange(2,8)
b=a*5
b




array([10, 15, 20, 25, 30, 35])

###### help(np.array)

In [129]:
sqrt=range(2,10)
x=np.array(sqrt)
z=x*x

print(z)

[ 4  9 16 25 36 49 64 81]


In [69]:
x=[(2,4,3),(3,2,4)]
w=np.array(x)
w[::-2]

array([[3, 2, 4]])

In [30]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [129]:
s=(6,5)
s=np.zeros((s),dtype=np.int)
print(s)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [131]:
s=(6,5)
a=np.ones((s[::2]),dtype=np.int)
b=np.zeros((s[0:1]),dtype=np.int)
print(a,b)

[1 1 1 1 1 1] [0 0 0 0 0 0]


In [77]:
# Method 1 >> using the list and coverting as in array

x=[(1,2,3,4,5),(3,4,5,6,7)] # Defined the value as list
y=[(10,20,30,40,10),(30,40,50,60,70)] # Defined the value as list
p=np.array(x) # Converting the List as Array for Axis-0
q=np.array(y) # Converting the list as Array for Axis-1
print(p,q)
p+q # Adding the Array as per assignment


[[1 2 3 4 5]
 [3 4 5 6 7]] [[10 20 30 40 10]
 [30 40 50 60 70]]


array([[11, 22, 33, 44, 15],
       [33, 44, 55, 66, 77]])

In [35]:
# Method 2 >> using direct method for creating Array 

p=np.array([[1,2,3,4,5],[3,4,5,6,7]],dtype=int) # Creating an Array for Axis-0
q=np.array([[10,20,30,40,50],[30,40,50,60,70]], dtype=int) # Creating as Array for Axis-1
print(p,q)
p+q # Adding the Array as per assignment

[[1 2 3 4 5]
 [3 4 5 6 7]] [[10 20 30 40 50]
 [30 40 50 60 70]]


array([[11, 22, 33, 44, 55],
       [33, 44, 55, 66, 77]])

In [97]:
import matplotlib.pyplot as plt

In [116]:

#plt.hist(z)
#plt.show()

In [3]:
a = np.array([[1,2,3],[4,5,6]]) 
#print (a.shape)
#print(np.shape(a))
a.shape=(3,2)
a
#print(np.shape=5,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
p=np.array([[1,2,3,4,5],[3,4,5,6,7]],dtype=int) # Creating an Array for Axis-0
q=np.array([[10,20,30,40,50],[30,40,50,60,70]], dtype=int) # Creating as Array for Axis-1

q.shape=(5,2)
#q.shape=(5,2)
#print (p,q)
#p+q

In [95]:
x = np.arange(9.).reshape(3, 3) 

print ('Our array is:' )
print ( x  )
print ( '\n'  )

print ('Indices of elements > 3' )
y = np.where(x > 3) 
print ("return diff array for row and column , we need to form indexes combining orresponding element")
print  (y )

#print ( '\n'  )

print ('Use these indices to get elements satisfying the condition' )
print (x[y])

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Indices of elements > 3
return diff array for row and column , we need to form indexes combining orresponding element
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


In [141]:
x = np.arange(1,12) 
y = 2 * x + 5 
print(y)
y=y[y%3!=0]
y.shape=(1,7)
#plt.title("Matplotlib demo") 
#plt.xlabel("x axis caption") 
#plt.ylabel("y axis caption") 
#plt.plot(x,y)
#plt.show()

[ 7  9 11 13 15 17 19 21 23 25 27]


In [6]:
a=np.array([5,8,9,0])
b=np.array([3,4,5,2])
a[2]=18
b[3]=25
a,b


(array([ 5,  8, 18,  0]), array([ 3,  4,  5, 25]))

In [184]:
a=np.array([5,8,9,0],dtype=float)
#a[:]=a+1.5
a+=3
a

array([ 8., 11., 12.,  3.])

In [152]:
b=np.arange(1,10)
b.shape=(3,3)
print(b)
a=np.arange(3)
b[a,a]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [24]:
from numpy.lib.stride_tricks import as_strided
#as_strided?
x = np.array([1, 2, 3, 4], dtype=np.int16)
x[::2]
x[::2].strides
as_strided(x, strides=(4,), shape=(2,))

array([1, 3], dtype=int16)

In [7]:
a=np.array([5,8,9,0,1,2],dtype=int)

#a>3
a[a>2]=-8
a

array([-8, -8, -8,  0,  1,  2])

In [59]:
a=np.array([5,8,9,0,1,2],dtype=int)
mask=a>2
b=a[mask]+5
a[mask]=b
a

array([10, 13, 14,  0,  1,  2])

In [88]:
a=np.arange(0,50)
a.shape=(5,10)
mask=a>25
b=a[mask]+150
a[mask]=b
#a
b=np.zeros_like(a)
b[mask]=a[mask]
b

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [148]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 18, 9]])
i = np.arange(3)
a[i,i]=8
a

array([[ 8,  2,  3],
       [ 4,  8,  6],
       [ 7, 18,  8]])

In [191]:
#a = np.array([[1, 2, 3], [4, 5, 6], [7, 18, 9]])
#i = np.arange(3)
a=np.random.zipf(1.3, size=(2,5))
a

array([[   7,   23,    1,   12,   10],
       [8326,    1,    1,    1,   12]])

In [214]:
s=np.dtype([('name', 'S20'), ('age','i1'), ('marks', 'f4')])

a=np.array([('Amit123', 15,30.78), ('Aadya', 17,80)], dtype=s)
print(a)


[(b'Amit123', 15, 30.78) (b'Aadya', 17, 80.  )]


In [4]:
s=np.arange(24)
s.shape=(3,2,4)
s.ndim
#s.itemsize
#s.reshape(4,3,2)
#s

3

In [277]:
x = np.array([1,2,3,4,5], dtype=np.int8)
x.itemsize

1

In [310]:
s=np.linspace(10,20,5)
s


array([10. , 12.5, 15. , 17.5, 20. ])

In [31]:
x = np.array([[1, 2,3,4],[5,6,7,8]])
y = x[[1,1],[0,3]]
print (x)
print(y)

[[1 2 3 4]
 [5 6 7 8]]
[5 8]


In [34]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print (a[~np.isnan(a)])


[1. 2. 3. 4. 5.]


In [75]:
x = np.array([[1, 2,3,4],[5,6,7,8]])
z=x.T
print(x)
print(z)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [102]:
x = np.array([[1, 2,3,4],[5,6,7,8]])
x=np.rollaxis(x,axis=1,start=0)
x

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
x = np.array([[1, 2,3,4],[5,6,7,8]])
x[0,2:]

array([3, 4])

In [3]:
x = np.array([[1, 2,3,4],[5,6,7,8]])
x[0:3,2:4]

array([[3, 4],
       [7, 8]])

In [20]:
x=np.arange(9)
#x.shape=(3,3)
print(x)
x[0::2]

[0 1 2 3 4 5 6 7 8]


array([0, 2, 4, 6, 8])

In [84]:
x=np.arange(0,60,5)
x=x.reshape(3,4)
y=np.array([1,2,3,4])
for x,y in np.nditer([x,y]):
    print('%d:%d'%(x,y)),

0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [5]:
x=np.arange(9)#.reshape(3,3)
x.shape=(3,3)
#x=input('abc')
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
a=np.arange(9)
a.shape=(3,3)
mask=a>4
d=[5]
#c=input()
#d.append(c)
b=a[mask]+d
a[mask]=b
#a
b=np.zeros_like(a)
b[mask]=a[mask]
b

array([[ 0,  0,  0],
       [ 0,  0, 10],
       [11, 12, 13]])

In [14]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
x+y


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [49]:
x=np.arange(9)
x.shape=(3,3)
print(x)
x = np.where(x>0)
x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [28]:
x=np.arange(10)
x.shape=(2,5)
print(x)
print(x[1:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]]


In [40]:
x=[1,2,3,4,5], [3,4,5,6,7], [4,5,6,7,8],[3,4,5,6,10]
print(x[0::][0:1])

([1, 2, 3, 4, 5],)


In [231]:
#x=np.arange(4).reshape(2,2)
#x.shape=(2,2)
y=np.arange(6,18)
y.shape=(4,3)
y

#np.concatenate((x,y))


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [77]:
# generate a password with length "passlen" with no duplicate characters in the password

import random

s = "abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()?"
passlen = 8
p =  "".join(random.sample(s,passlen ))
print (p)

89pk%K^?


In [82]:
import random

characters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '!', '@', '#', '$', '%', '&', '*', '(', ')']

strength = input("Do you want a weak, medium, or strong, password?: ").lower()

new_password = []

def password(strength):
    if strength == 'weak':#First we'll define the strength
        while len(new_password) != 5:
            new_password.append(characters[random.randint(1, 70)])
    elif strength == 'medium':
        while len(new_password) != 8:
            new_password.append(characters[random.randint(1, 70)])
    elif strength == 'strong':
        while len(new_password) != 14:
            new_password.append(characters[random.randint(1, 70)])
    return new_password

password(strength)

new_password = "".join(new_password)

print(new_password)

Do you want a weak, medium, or strong, password?:  strong


ohWjkVqyqp$7W9


In [91]:
x=np.zeros(10)
y=np.arange(10)
y.itemsize*y.size

40

In [94]:
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [117]:
#y=np.arange(0,9)
#y.shape=(3,3)
z=np.arange(9)
x,y =z.min(), z.max()
print(z)
p=z.mean()
print(p)

[0 1 2 3 4 5 6 7 8]
4.0


In [7]:
Z = np.ones((10,10))

Z[1:-1,1:-1] = 4
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 4. 4. 4. 4. 4. 4. 4. 4. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [9]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [10]:
x+=np.arange(9)
x.reshape(3,3)
x

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32])

In [125]:
Z = np.diag(1+np.arange(5),k=-1)
print(Z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [136]:
Z = np.zeros((8,8),dtype=int)
Z[::2,1::2]=1
Z[1::2,::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [142]:
Z = np.dot(np.ones((5,4)), np.ones((4,2)))
print(Z)

[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


In [145]:
x=np.arange(9)
x[(x>3) & (x<8)]=-1
x

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8])

In [151]:
Z=np.arange(25)
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1


In [152]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [159]:
#Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]
 [0. 2. 4. 6. 8.]]


In [186]:
s=np.ones((3,3))
s+=np.arange(3)
s

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [4]:
x=np.arange((9))
y=x+5
x,y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13]))

In [210]:
phi = np.arange(0, 5*np.pi, .5)
phi

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5])

In [217]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [13]:
A = np.random.randint(0,9,(8,3))
B = np.random.randint(0,5,(2,2))
A,B

(array([[6, 3, 0],
        [7, 5, 2],
        [8, 5, 7],
        [8, 7, 0],
        [6, 7, 0],
        [3, 2, 5],
        [3, 1, 4],
        [8, 7, 1]]), array([[0, 2],
        [2, 2]]))

In [191]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]
